version: '3.8'
services:
  frontend:
    image: yourdockerhubuser/my-frontend:latest
    container_name: my-frontend
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
